version: "3.8"

services:
  text2light:
    build: .
    hostname: text2light
    container_name: text2light
    privileged: true
#    ports:
#      - "6006:6006"
    stdin_open: true
    tty: true
    shm_size: '2gb'
    volumes:
      - .:/workspace
      - /home-local2/iamaq.extra.nobkp/datasets/outdoorPanosExr:/workspace/outdoorPanosExr
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # count: 1
              device_ids: ['0']
              capabilities: [gpu]
